version: "3.3"
services:
  app:
    image: infracloudio/csvserver:latest
    ports:
     - 9393:9300
    volumes:
      - /home/ubuntu/csvserver/solution/inputFile:/csvserver/inputdata
    environment:
     CSVSERVER_BORDER: Orange
  Prometheus:
    image: prom/prometheus:v2.22.0
    ports: 
     - 9090:9090
    volumes:
     - /home/ubuntu/csvserver/solution/prometheus.yml:/etc/prometheus/prometheus.yml
